const worldCup2026Groups = [
  {
    label: "Grupa A",
    teams: [
      { name: "Mexico", flag: "🇲🇽" },
      { name: "South Africa", flag: "🇿🇦" },
      { name: "South Korea", flag: "🇰🇷" },
      { name: "Czech Republic", flag: "🇨🇿" },
    ],
  },
  {
    label: "Grupa B",
    teams: [
      { name: "Canada", flag: "🇨🇦" },
      { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
      { name: "Qatar", flag: "🇶🇦" },
      { name: "Switzerland", flag: "🇨🇭" },
    ],
  },
  {
    label: "Grupa C",
    teams: [
      { name: "Brazil", flag: "🇧🇷" },
      { name: "Morocco", flag: "🇲🇦" },
      { name: "Haiti", flag: "🇭🇹" },
      { name: "Scotland", flagType: "scotland", flagLabel: "Scotland flag" },
    ],
  },
  {
    label: "Grupa D",
    teams: [
      { name: "United States", flag: "🇺🇸" },
      { name: "Paraguay", flag: "🇵🇾" },
      { name: "Australia", flag: "🇦🇺" },
      { name: "Turkey", flag: "🇹🇷" },
    ],
  },
  {
    label: "Grupa E",
    teams: [
      { name: "Germany", flag: "🇩🇪" },
      { name: "Curacao", flag: "🇨🇼" },
      { name: "Ivory Coast", flag: "🇨🇮" },
      { name: "Ecuador", flag: "🇪🇨" },
    ],
  },
  {
    label: "Grupa F",
    teams: [
      { name: "Netherlands", flag: "🇳🇱" },
      { name: "Japan", flag: "🇯🇵" },
      { name: "Sweden", flag: "🇸🇪" },
      { name: "Tunisia", flag: "🇹🇳" },
    ],
  },
  {
    label: "Grupa G",
    teams: [
      { name: "Belgium", flag: "🇧🇪" },
      { name: "Egypt", flag: "🇪🇬" },
      { name: "Iran", flag: "🇮🇷" },
      { name: "New Zealand", flag: "🇳🇿" },
    ],
  },
  {
    label: "Grupa H",
    teams: [
      { name: "Spain", flag: "🇪🇸" },
      { name: "Cape Verde", flag: "🇨🇻" },
      { name: "Saudi Arabia", flag: "🇸🇦" },
      { name: "Uruguay", flag: "🇺🇾" },
    ],
  },
  {
    label: "Grupa I",
    teams: [
      { name: "France", flag: "🇫🇷" },
      { name: "Senegal", flag: "🇸🇳" },
      { name: "Iraq", flag: "🇮🇶" },
      { name: "Norway", flag: "🇳🇴" },
    ],
  },
  {
    label: "Grupa J",
    teams: [
      { name: "Argentina", flag: "🇦🇷" },
      { name: "Algeria", flag: "🇩🇿" },
      { name: "Austria", flag: "🇦🇹" },
      { name: "Jordan", flag: "🇯🇴" },
    ],
  },
  {
    label: "Grupa K",
    teams: [
      { name: "Portugal", flag: "🇵🇹" },
      { name: "DR Congo", flag: "🇨🇩" },
      { name: "Uzbekistan", flag: "🇺🇿" },
      { name: "Colombia", flag: "🇨🇴" },
    ],
  },
  {
    label: "Grupa L",
    teams: [
      { name: "England", flagType: "england", flagLabel: "England flag" },
      { name: "Croatia", flag: "🇭🇷" },
      { name: "Ghana", flag: "🇬🇭" },
      { name: "Panama", flag: "🇵🇦" },
    ],
  },
];

window.SPECIAL_CATEGORY_LAYOUTS = {
  "world-cup-2026": {
    groups: worldCup2026Groups,
  },
};

window.CATALOG = {
  "premier-league": {
    section: "dresovi",
    label: "Premier League",
    logo: "images/logos/premier-league.png",
    teams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Sunderland",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Burnley",
      "Tottenham",
      "West Ham United",
      "Wolverhampton",
    ],
  },
  bundesliga: {
    section: "dresovi",
    label: "Bundesliga",
    logo: "images/logos/bundesliga.png",
    teams: [
      "Bayern Munich",
      "Borussia Dortmund",
      "RB Leipzig",
      "Bayer Leverkusen",
      "Stuttgart",
      "Eintracht Frankfurt",
      "Wolfsburg",
      "Borussia Monchengladbach",
      "Werder Bremen",
      "Hoffenheim",
      "Mainz",
      "Freiburg",
      "Augsburg",
      "Union Berlin",
      "Heidenheim",
      "HSV",
      "St Pauli",
      "1. FC Koln",
    ],
  },
  "serie-a": {
    section: "dresovi",
    label: "Serie A",
    logo: "images/logos/serie-a.png",
    teams: [
      "AC Milan",
      "Inter",
      "Juventus",
      "Napoli",
      "Roma",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "Bologna",
      "Torino",
      "Genoa",
      "Sassuolo",
      "Parma",
      "Udinese",
      "Pisa",
      "Cagliari",
      "Como",
      "Cremonese",
      "Lecce",
      "Hellas Verona",
    ],
  },
  "mystery-box-sp2026": {
    section: "svetsko-prvenstvo",
    label: "Mystery Box - Svetsko prvenstvo 2026",
    logo: "images/logos/world-cup-2026.png",
    featured: true,
    teams: [],
  },
  "world-cup-2026-staro": {
    section: "svetsko-prvenstvo",
    label: "Svetsko prvenstvo 2026 - svi dresovi",
    logo: "images/logos/world-cup-2026.png",
    teams: [],
  },
  "world-cup-2026-deciji-kompleti": {
    section: "svetsko-prvenstvo",
    label: "Svetsko prvenstvo 2026 - Dečiji kompleti",
    logo: "images/logos/world-cup-2026.png",
    teams: [],
  },
  "world-cup-2026": {
    section: "svetsko-prvenstvo",
    label: "Svetsko prvenstvo 2026 - po grupama",
    logo: "images/logos/world-cup-2026.png",
    teams: worldCup2026Groups.reduce((allTeams, group) => {
      group.teams.forEach((team) => allTeams.push(team.name));
      return allTeams;
    }, []),
  },
  "ligue-1": {
    section: "dresovi",
    label: "Ligue 1",
    logo: "images/logos/ligue-1.png",
    teams: [
      "Paris Saint Germain",
      "Marseille",
      "Lyon",
      "Monaco",
      "Lille",
      "Nice",
      "Lens",
      "Rennes",
      "Nantes",
      "Lorient",
      "Paris FC",
      "Toulouse",
      "Strasbourg",
      "Brest",
      "Metz",
      "Le Havre",
      "Angers",
      "Auxerre",
    ],
  },
  "la-liga": {
    section: "dresovi",
    label: "La Liga",
    logo: "images/logos/la-liga.png",
    teams: [
      "Real Madrid",
      "Barcelona",
      "Atletico Madrid",
      "Sevilla",
      "Valencia",
      "Real Betis",
      "Real Sociedad",
      "Villarreal",
      "Athletic Bilbao",
      "Girona",
      "Getafe",
      "Celta Vigo",
      "Osasuna",
      "Mallorca",
      "Levante",
      "Espanyol",
      "Rayo Vallecano",
      "Alaves",
      "Elche",
      "Oviedo",
    ],
  },
  "other-european-clubs": {
    section: "dresovi",
    label: "Ostali evropski timovi",
    teams: [],
  },
  "other-national-teams": {
    section: "dresovi",
    label: "Repke - retro dresovi",
    logo: "images/logos/other-national-teams.png",
    teams: [],
  },
  nba: {
    section: "dresovi",
    label: "NBA",
    logo: "images/logos/nba.png",
    teams: [
      "Atlanta Hawks",
      "Boston Celtics",
      "Brooklyn Nets",
      "Charlotte Hornets",
      "Chicago Bulls",
      "Cleveland Cavaliers",
      "Dallas Mavericks",
      "Denver Nuggets",
      "Detroit Pistons",
      "Golden State Warriors",
      "Houston Rockets",
      "Indiana Pacers",
      "LA Clippers",
      "Los Angeles Lakers",
      "Memphis Grizzlies",
      "Miami Heat",
      "Milwaukee Bucks",
      "Minnesota Timberwolves",
      "New Orleans Pelicans",
      "New York Knicks",
      "Oklahoma City Thunder",
      "Orlando Magic",
      "Philadelphia 76ers",
      "Phoenix Suns",
      "Portland Trail Blazers",
      "Sacramento Kings",
      "San Antonio Spurs",
      "Toronto Raptors",
      "Utah Jazz",
      "Washington Wizards",
    ],
  },
  euroleague: {
    section: "dresovi",
    label: "Euroleague",
    logo: "images/logos/euroleague.png",
    teams: [],
  },
  "other-sports": {
    section: "hidden",
    label: "Ostali sportovi",
    teams: [
      "Formula 1 Ferrari",
      "Formula 1 Mercedes",
      "Formula 1 Red Bull Racing",
      "Formula 1 McLaren",
      "Formula 1 Aston Martin",
      "NFL Kansas City Chiefs",
      "NFL San Francisco 49ers",
      "NFL Dallas Cowboys",
      "NFL New York Giants",
      "MLB New York Yankees",
      "MLB Los Angeles Dodgers",
      "NHL New York Rangers",
      "NHL Toronto Maple Leafs",
      "Tennis",
      "Rugby",
      "Baseball",
      "Hockey",
    ],
  },
  "trening-kompleti": {
    section: "trening",
    label: "Trening kompleti",
    teams: [],
  },
  "trening-komplet-sorc-majica": {
    section: "trening",
    label: "Trening komplet šorc i majica",
    teams: [],
  },
  "trening-majice": {
    section: "trening",
    label: "Trening majice",
    teams: [],
  },
  duksevi: {
    section: "trening",
    label: "Duksevi",
    teams: [],
  },
  "dresovi-na-stanju": {
    section: "trening",
    label: "Dresovi na stanju",
    teams: [],
  },
  "trenerke-za-setnju": {
    section: "trening",
    label: "Trenerke za šetnju",
    teams: [],
  },
  "trenerke-sa-kapuljacom": {
    section: "trening",
    label: "Trenerke sa kapuljačom",
    teams: [],
  },
};

window.CATALOG_SECTIONS = {
  "svetsko-prvenstvo": { label: "Svetsko prvenstvo" },
  dresovi: { label: "Dresovi" },
  trening: { label: "Trening asortiman" },
};

window.CONTACT = {
  whatsappNumber: "381654553249",
  viberNumber: "+381654553249",
  viberGroupLink:
    "https://invite.viber.com/?g2=AQAXbnOmV4qPNVRSiixrDjg5HSojFfS7Rp0l1DxzG0hA%252Bu0uTyV5KmsLhU%252BR9KaV",
};

window.PINNED_PRODUCT_CODES = {
  "serie-a/ac-milan": ["SER-ACM-098", "SER-ACM-184"],
  // Primer kljuca za tim: "serie-a/inter": ["SER-INT-004", "SER-INT-007"],
  // Primer kljuca za kategoriju bez timova: "world-cup-2026": ["WOR-CAT-001"],
};
