window.CATALOG = {
  "premier-league": {
    section: "dresovi",
    label: "Premier League",
    logo: "images/logos/premier-league.png",
    teams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Sunderland",
      "Leeds United",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Burnley",
      "Tottenham",
      "West Ham United",
      "Wolverhampton",
    ],
  },
  bundesliga: {
    section: "dresovi",
    label: "Bundesliga",
    logo: "images/logos/bundesliga.png",
    teams: [
      "Bayern Munich",
      "Borussia Dortmund",
      "RB Leipzig",
      "Bayer Leverkusen",
      "Stuttgart",
      "Eintracht Frankfurt",
      "Wolfsburg",
      "Borussia Monchengladbach",
      "Werder Bremen",
      "Hoffenheim",
      "Mainz",
      "Freiburg",
      "Augsburg",
      "Union Berlin",
      "Heidenheim",
      "HSV",
      "St Pauli",
      "1. FC Koln",
    ],
  },
  "serie-a": {
    section: "dresovi",
    label: "Serie A",
    logo: "images/logos/serie-a.png",
    teams: [
      "AC Milan",
      "Inter",
      "Juventus",
      "Napoli",
      "Roma",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "Bologna",
      "Torino",
      "Genoa",
      "Sassuolo",
      "Parma",
      "Udinese",
      "Pisa",
      "Cagliari",
      "Como",
      "Cremonese",
      "Lecce",
      "Hellas Verona",
    ],
  },
  "world-cup-2026": {
    section: "dresovi",
    label: "World Cup 2026",
    logo: "images/logos/world-cup-2026.png",
    teams: [],
  },
  "ligue-1": {
    section: "dresovi",
    label: "Ligue 1",
    logo: "images/logos/ligue-1.png",
    teams: [
      "Paris Saint Germain",
      "Marseille",
      "Lyon",
      "Monaco",
      "Lille",
      "Nice",
      "Lens",
      "Rennes",
      "Nantes",
      "Lorient",
      "Paris FC",
      "Toulouse",
      "Strasbourg",
      "Brest",
      "Metz",
      "Le Havre",
      "Angers",
      "Auxerre",
    ],
  },
  "la-liga": {
    section: "dresovi",
    label: "La Liga",
    logo: "images/logos/la-liga.png",
    teams: [
      "Real Madrid",
      "Barcelona",
      "Atletico Madrid",
      "Sevilla",
      "Valencia",
      "Real Betis",
      "Real Sociedad",
      "Villarreal",
      "Athletic Bilbao",
      "Girona",
      "Getafe",
      "Celta Vigo",
      "Osasuna",
      "Mallorca",
      "Levante",
      "Espanyol",
      "Rayo Vallecano",
      "Alaves",
      "Elche",
      "Oviedo",
    ],
  },
  "other-european-clubs": {
    section: "dresovi",
    label: "Ostali evropski timovi",
    teams: [],
  },
  "other-national-teams": {
    section: "dresovi",
    label: "Ostale repke",
    logo: "images/logos/other-national-teams.png",
    teams: [],
  },
  nba: {
    section: "dresovi",
    label: "NBA",
    logo: "images/logos/nba.png",
    teams: [
      "Atlanta Hawks",
      "Boston Celtics",
      "Brooklyn Nets",
      "Charlotte Hornets",
      "Chicago Bulls",
      "Cleveland Cavaliers",
      "Dallas Mavericks",
      "Denver Nuggets",
      "Detroit Pistons",
      "Golden State Warriors",
      "Houston Rockets",
      "Indiana Pacers",
      "LA Clippers",
      "Los Angeles Lakers",
      "Memphis Grizzlies",
      "Miami Heat",
      "Milwaukee Bucks",
      "Minnesota Timberwolves",
      "New Orleans Pelicans",
      "New York Knicks",
      "Oklahoma City Thunder",
      "Orlando Magic",
      "Philadelphia 76ers",
      "Phoenix Suns",
      "Portland Trail Blazers",
      "Sacramento Kings",
      "San Antonio Spurs",
      "Toronto Raptors",
      "Utah Jazz",
      "Washington Wizards",
    ],
  },
  euroleague: {
    section: "dresovi",
    label: "Euroleague",
    logo: "images/logos/euroleague.png",
    teams: [],
  },
  "other-sports": {
    section: "hidden",
    label: "Ostali sportovi",
    teams: [
      "Formula 1 Ferrari",
      "Formula 1 Mercedes",
      "Formula 1 Red Bull Racing",
      "Formula 1 McLaren",
      "Formula 1 Aston Martin",
      "NFL Kansas City Chiefs",
      "NFL San Francisco 49ers",
      "NFL Dallas Cowboys",
      "NFL New York Giants",
      "MLB New York Yankees",
      "MLB Los Angeles Dodgers",
      "NHL New York Rangers",
      "NHL Toronto Maple Leafs",
      "Tennis",
      "Rugby",
      "Baseball",
      "Hockey",
    ],
  },
  "trening-kompleti": {
    section: "trening",
    label: "Trening kompleti",
    teams: [],
  },
  "trening-komplet-sorc-majica": {
    section: "trening",
    label: "Trening komplet šorc i majica",
    teams: [],
  },
  "trening-majice": {
    section: "trening",
    label: "Trening majice",
    teams: [],
  },
  duksevi: {
    section: "trening",
    label: "Duksevi",
    teams: [],
  },
  "trenerke-za-setnju": {
    section: "trening",
    label: "Trenerke za šetnju",
    teams: [],
  },
  "trenerke-sa-kapuljacom": {
    section: "trening",
    label: "Trenerke sa kapuljačom",
    teams: [],
  },
};

window.CATALOG_SECTIONS = {
  dresovi: { label: "Dresovi" },
  trening: { label: "Trening asortiman" },
};

window.CONTACT = {
  whatsappNumber: "381654553249",
  viberNumber: "+381654553249",
  viberGroupLink:
    "https://invite.viber.com/?g2=AQAXbnOmV4qPNVRSiixrDjg5HSojFfS7Rp0l1DxzG0hA%252Bu0uTyV5KmsLhU%252BR9KaV",
};

window.PINNED_PRODUCT_CODES = {
  "serie-a/ac-milan": ["SER-ACM-098", "SER-ACM-184"],
  // Primer kljuca za tim: "serie-a/inter": ["SER-INT-004", "SER-INT-007"],
  // Primer kljuca za kategoriju bez timova: "world-cup-2026": ["WOR-CAT-001"],
};
