window.CATALOG = {
  "premier-league": {
    label: "Premier League",
    teams: [
      "Arsenal",
      "Aston Villa",
      "Bournemouth",
      "Brentford",
      "Brighton",
      "Chelsea",
      "Crystal Palace",
      "Everton",
      "Fulham",
      "Ipswich Town",
      "Leicester City",
      "Liverpool",
      "Manchester City",
      "Manchester United",
      "Newcastle United",
      "Nottingham Forest",
      "Southampton",
      "Tottenham",
      "West Ham United",
      "Wolverhampton",
    ],
  },
  bundesliga: {
    label: "Bundesliga",
    teams: [
      "Bayern Munich",
      "Borussia Dortmund",
      "RB Leipzig",
      "Bayer Leverkusen",
      "Stuttgart",
      "Eintracht Frankfurt",
      "Wolfsburg",
      "Borussia Monchengladbach",
      "Werder Bremen",
      "Hoffenheim",
      "Mainz",
      "Freiburg",
      "Augsburg",
      "Union Berlin",
      "Heidenheim",
      "Bochum",
      "St Pauli",
      "Holstein Kiel",
    ],
  },
  "serie-a": {
    label: "Serie A",
    teams: [
      "AC Milan",
      "Inter",
      "Juventus",
      "Napoli",
      "Roma",
      "Lazio",
      "Atalanta",
      "Fiorentina",
      "Bologna",
      "Torino",
      "Genoa",
      "Sampdoria",
      "Parma",
      "Udinese",
      "Empoli",
      "Cagliari",
      "Como",
      "Monza",
      "Lecce",
      "Verona",
    ],
  },
  "world-cup-2026": {
    label: "World Cup 2026",
    teams: [
      "Argentina",
      "Brazil",
      "France",
      "England",
      "Spain",
      "Germany",
      "Italy",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Croatia",
      "Serbia",
      "Uruguay",
      "Mexico",
      "USA",
      "Canada",
      "Japan",
      "South Korea",
      "Morocco",
      "Turkey",
    ],
  },
  "ligue-1": {
    label: "Ligue 1",
    teams: [
      "Paris Saint Germain",
      "Marseille",
      "Lyon",
      "Monaco",
      "Lille",
      "Nice",
      "Lens",
      "Rennes",
      "Nantes",
      "Saint Etienne",
      "Montpellier",
      "Toulouse",
      "Strasbourg",
      "Brest",
      "Reims",
      "Le Havre",
      "Angers",
      "Auxerre",
    ],
  },
  "la-liga": {
    label: "La Liga",
    teams: [
      "Real Madrid",
      "Barcelona",
      "Atletico Madrid",
      "Sevilla",
      "Valencia",
      "Real Betis",
      "Real Sociedad",
      "Villarreal",
      "Athletic Bilbao",
      "Girona",
      "Getafe",
      "Celta Vigo",
      "Osasuna",
      "Mallorca",
      "Las Palmas",
      "Espanyol",
      "Rayo Vallecano",
      "Alaves",
      "Leganes",
      "Valladolid",
    ],
  },
  "other-european-clubs": {
    label: "Ostali evropski timovi",
    teams: [
      "Ajax",
      "PSV",
      "Feyenoord",
      "Porto",
      "Benfica",
      "Sporting CP",
      "Celtic",
      "Rangers",
      "Galatasaray",
      "Fenerbahce",
      "Besiktas",
      "Red Star Belgrade",
      "Partizan",
      "Dinamo Zagreb",
      "Shakhtar Donetsk",
      "Olympiacos",
      "Panathinaikos",
      "Club Brugge",
      "Anderlecht",
      "RB Salzburg",
      "Young Boys",
      "Sparta Prague",
      "Slavia Prague",
      "Ferencvaros",
      "FC Copenhagen",
      "Malmo",
    ],
  },
  "other-national-teams": {
    label: "Ostale reprezentacije",
    teams: [
      "Serbia",
      "Croatia",
      "Bosnia and Herzegovina",
      "Slovenia",
      "Montenegro",
      "North Macedonia",
      "Albania",
      "Switzerland",
      "Austria",
      "Poland",
      "Czech Republic",
      "Denmark",
      "Sweden",
      "Norway",
      "Scotland",
      "Wales",
      "Ireland",
      "Ukraine",
      "Greece",
      "Romania",
      "Hungary",
      "Colombia",
      "Chile",
      "Peru",
      "Nigeria",
      "Ghana",
      "Cameroon",
      "Algeria",
      "Tunisia",
      "Australia",
    ],
  },
  nba: {
    label: "NBA",
    teams: [
      "Atlanta Hawks",
      "Boston Celtics",
      "Brooklyn Nets",
      "Charlotte Hornets",
      "Chicago Bulls",
      "Cleveland Cavaliers",
      "Dallas Mavericks",
      "Denver Nuggets",
      "Detroit Pistons",
      "Golden State Warriors",
      "Houston Rockets",
      "Indiana Pacers",
      "LA Clippers",
      "Los Angeles Lakers",
      "Memphis Grizzlies",
      "Miami Heat",
      "Milwaukee Bucks",
      "Minnesota Timberwolves",
      "New Orleans Pelicans",
      "New York Knicks",
      "Oklahoma City Thunder",
      "Orlando Magic",
      "Philadelphia 76ers",
      "Phoenix Suns",
      "Portland Trail Blazers",
      "Sacramento Kings",
      "San Antonio Spurs",
      "Toronto Raptors",
      "Utah Jazz",
      "Washington Wizards",
    ],
  },
  euroleague: {
    label: "EuroLeague",
    teams: [
      "Real Madrid Basketball",
      "Barcelona Basketball",
      "Partizan Basketball",
      "Red Star Basketball",
      "Panathinaikos Basketball",
      "Olympiacos Basketball",
      "Fenerbahce Basketball",
      "Anadolu Efes",
      "Maccabi Tel Aviv",
      "Baskonia",
      "Valencia Basket",
      "Monaco Basketball",
      "Virtus Bologna",
      "Olimpia Milano",
      "Bayern Basketball",
      "Zalgiris",
      "ASVEL",
      "Paris Basketball",
    ],
  },
  "other-sports": {
    label: "Ostali sportovi",
    teams: [
      "Formula 1 Ferrari",
      "Formula 1 Mercedes",
      "Formula 1 Red Bull Racing",
      "Formula 1 McLaren",
      "Formula 1 Aston Martin",
      "NFL Kansas City Chiefs",
      "NFL San Francisco 49ers",
      "NFL Dallas Cowboys",
      "NFL New York Giants",
      "MLB New York Yankees",
      "MLB Los Angeles Dodgers",
      "NHL New York Rangers",
      "NHL Toronto Maple Leafs",
      "Tennis",
      "Rugby",
      "Baseball",
      "Hockey",
    ],
  },
};
